version: '3.8'


services:
  app:
    build:
      context: .
    image: adcoiffure-docker
    ports:
      - "5000"
    restart: unless-stopped

  nginx:
      image: nginx:latest
      volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/adcoiffure.com/fullchain1.pem:/etc/nginx/fullchain.pem:ro
      - /etc/letsencrypt/archive/adcoiffure.com/privkey1.pem:/etc/nginx/privkey.pem:ro
      depends_on:
      - app
      ports:
      - "80:80"
      - "443:443"
      restart: unless-stopped